---
title: "Imdad Hussain BH"
author: "DevOps Engineer"
output:
  rmdformats::material:
    highlight: kate
    cards: false
    self_contained: no
---


```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(rmdformats)


## Global options
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# About Me

* 4.3 years of experience in IT industry working across multiple teams as a DevOps Engineer

* Experience working on Linux based environments hosted across On-premise and Cloud Infrastructure

* Good knowledge in scripting languages - Bash, Groovy and Python

* Implemented solutions for DevSecOps including security scanning as part of build pipeline using Veracode and ZAP tool

* Worked on containerization using Docker and orchestrating it with Rancher, Kubernetes


# Work Experience

### Wipro Digital (Lloyds Banking Group): FAL Team - Platform Engineer
#### August 2018 - Present (1 year 2 months and counting)

* Led the lab as a Platform engineer and enabled multiple feature teams with DevOps toolchain
* Responsible for managing and implementing DevOps solutions for both Offshore and Onshore, engaging with multiple feature teams
* Implemented logging mechanism using ELK stack for the DEV platform which has around 50 microservices
* Created a docker-compose for setting up the pact broker to perform contract testing
* Built Grafana dashboards for monitoring of cloud-hosted VM's and applications and used Prometheus for scraping the metrics from various targets
* Created an ELK stack across the VM's for retrieving the logs from multiple microservices
* Integrated contract testing as part of build pipeline
* Created a pipeline job for BDD framework used by QA teams to run their regression test suites on-demand 
* Enabled performance testing for microservices using Gatling as part of build pipeline to ensure the application is performing as expected with the new changes
* Managed upgradation of SonarQube and Nexus application which has been hosted in Docker containers
* Troubleshot broken DB issues with Nexus by following the appropriate procedure and restored it back
* Added DAST testing as part of Jenkins pipeline using ZAP to generate the report which lists the alerts and its severity
* Created multiple EC2 instances and have executed playbooks for configuring it using Ansible
* Worked with AWS lambda for running functions on-demand using python


### Wipro Digital (Lloyds Banking Group): Fraud Team - DevOps Engineer
#### January 2017 - June 2018 (1 year 6 months)

* Built and managed DevOps Platform on IBM Cloud
* Worked on migration between on-premise and cloud infrastructure
* Involved in creating and managing various tools such as Jenkins, Nexus, SonarQube, GHE, Gitlab, Pact Broker, Microservices
* Used Rancher and Kubernetes for managing Docker containers hosted on cloud VM's
* Migrated Jenkins jobs from legacy (1.x) to pipeline (2.x) using Declarative pipeline
* Worked with LetsEncrypt of AWS to attach certificates for the DNS
* Created and managed users with their roles using Red Hat Identity Manager
* Added deployment functionality with Jenkins pipeline onto IBM Urban Code Deploy
* Implemented Persistent storage for Docker containers with Portworx
* Migrated volumes across VM's by manipulating the nodes cluster
* Provided support for the development team to go through RTL process
* Demonstrated the implementation of Rancher 2 and k8s to the clients for engineering interventions
* Worked with MySQL for retrieving reco5 rds from database


### Wipro Digital (Lloyds Banking Group): Central Team - DevOps Engineer
#### September 2015 - December 2016 (1 year 3 months)
* Integrated Jenkins Build with Code Quality and deployed the artifacts into Nexus Repository
* Worked with GitHub REST API for managing users and adding to organization
* Added Jenkins jobs for various components of a monolithic application and enabled a continuous integration at each level
* Created roles in Ansible based on the purpose and segregated it for re-using it with multiple playbooks
* Wrote Ansible playbooks for configuring Linux VM's and provisioning it to the feature teams for simulating the behavior of Dev environments
* Created and maintained Jenkins Job using groovy and bash scripting
* Configured repositories in Nexus artefactory which include proxy and hosted repository
* Enabled threshold metrics in SonarQube to act as a quality gate which checks for any major issues and reports back to the teams
* Wrote cron jobs for Linux environment to clean up the storage based on the given requirements
* Provided documentation using confluence for the development teams to make them self sufficient
* Fixed frequent occurring issues in VM's by analyzing the root cause and automated the process using bash scripting
* Created Jenkins job for automation of webhooks configuration which will get trigger whenever a commit happens in Gerrit
* Worked with Gerrit for managing the source code, added hooks for auto labeling the commits 
* Used SQL queries to update the Gerrit Database using DML transactions


# Master's thesis project

### NLP for aiding Scientific Literature Curation (April 2019 - August 2019)
The huge amount of information in the Scientific research literature has presented us with a challenge of curating, integrating and summarizing it into a structured data model, that can be used for various meta analyses and to provide a brief summary snapshot of any given scientific area. This project aimed to develop an application that uses NLP (Natural Language Processing) based approaches to mine documents from scientific literature, process and extract relevant information, organize the information into a structured form and provide a summarization to help researchers by reducing the time for manual curation. This application processes the bulk literature documents provided by the user, performs analysis and provides summary of them, among other things.


# Technical Skills

### DevOps
#### CI/CD, Jenkins, Docker, Rancher, k8s, Ansible , Nexus, Sonar, Terraform

### Scripting languages
#### Python, Bash, Groovy

# Additional Skills

* Fundamental understanding of Natural Language Processing and its applications
* Knowledge of various levels of testing and its scope
* Presented a talk at JFrog India on "Jenkins Nightmare and How I saved my Day"
* Explored various services provided by Google Cloud platform, Amazon Web Services
* Contributed to few open source projects in GitHub
* Completed certification in IBM Bluemix Developer v2
* Built Proof Of Concept's and demonstrated to clients

# Education

### M.Tech (Integrated) - Information Technology (2015 - 2019)
VIT University, Vellore, India 

As part of Wipro Software Technology Academy (Wista) programme

### B.Sc., Computer Science (2012 - 2015)
Thiruvalluvar University, Vellore, India

# Personal Information

Languages	    : English (Proficient), Tamil (Native), Urdu (Native)
		            
Mobile	      : +91 8148 00 3494

Email	      	: 003imdad@gmail.com

[GitHub](github.com/hussain-devops)
  
[LinkedIn](www.linkedin.com/in/imdad-hussain-devops/)
